//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerTitan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowerTitan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during database connection.
        ///.
        /// </summary>
        internal static string Database_error_text {
            get {
                return ResourceManager.GetString("Database_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        internal static string Database_error_title {
            get {
                return ResourceManager.GetString("Database_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted..
        /// </summary>
        internal static string MainWindow_status_abort {
            get {
                return ResourceManager.GetString("MainWindow_status_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string MainWindow_status_done {
            get {
                return ResourceManager.GetString("MainWindow_status_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported..
        /// </summary>
        internal static string MainWindow_status_export {
            get {
                return ResourceManager.GetString("MainWindow_status_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported..
        /// </summary>
        internal static string MainWindow_status_import {
            get {
                return ResourceManager.GetString("MainWindow_status_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string MainWindow_status_importing {
            get {
                return ResourceManager.GetString("MainWindow_status_importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded..
        /// </summary>
        internal static string MainWindow_status_load {
            get {
                return ResourceManager.GetString("MainWindow_status_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MainWindow_status_loading {
            get {
                return ResourceManager.GetString("MainWindow_status_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string MainWindow_status_processing {
            get {
                return ResourceManager.GetString("MainWindow_status_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string MainWindow_status_ready {
            get {
                return ResourceManager.GetString("MainWindow_status_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        internal static string MainWindow_status_save {
            get {
                return ResourceManager.GetString("MainWindow_status_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string MainWindow_status_saving {
            get {
                return ResourceManager.GetString("MainWindow_status_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMB - new point/new line/select point
        ///RMB - end of line/deselect
        ///LMB pressed - move point
        ///DEL - delete current point
        ///BACKSPACE - delete whole line.
        /// </summary>
        internal static string MeasuringLines_help {
            get {
                return ResourceManager.GetString("MeasuringLines_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load template.
        /// </summary>
        internal static string Open_load {
            get {
                return ResourceManager.GetString("Open_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load lines from template.
        /// </summary>
        internal static string Open_load_template {
            get {
                return ResourceManager.GetString("Open_load_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        internal static string Open_status_deleting {
            get {
                return ResourceManager.GetString("Open_status_deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during template generation..
        /// </summary>
        internal static string TemplateGenerator_error_text {
            get {
                return ResourceManager.GetString("TemplateGenerator_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator error.
        /// </summary>
        internal static string TemplateGenerator_error_title {
            get {
                return ResourceManager.GetString("TemplateGenerator_error_title", resourceCulture);
            }
        }
    }
}
